### ISSUE TITLE
New interface

### ISSUE THREAD

**Issue by TheBigRaph1990** [MscrmTools/MsCrmTools.ChartManager#2]
Salut,

Est-ce que Chart Manager fonctionnera avec la nouvelle interface de D365 ? 

Merci de votre retour,

**Comment by MscrmTools** [comment]
Bonjour, 
Aucune raison que ça ne soit pas le cas. Mais si ça doit ne pas fonctionner, ça sera parce que Microsoft n'aura pas implémenté toutes les fonctionnalités de l'interface classique dans la nouvelle interface

**Comment by TheBigRaph1990** [comment]
Bonjour,

Pour le moment cela ne fonctionne pas … avec la nouvelle interface les couleurs des graphiques sont redevenues bleu (couleurs par défaut) ...

**Comment by MscrmTools** [comment]
Oui, c'est donc un problème côté Microsoft, pas Chart Manager

**Comment by TheBigRaph1990** [comment]
Ok ! Merci

**Comment by MscrmTools** [comment]
Puis je vous suggérer de ne pas répondre par email ou d'enlever votre numéro de téléphone portable de votre signature pour éviter de vous faire spammer :)

**Comment by TheBigRaph1990** [comment]
Merci de cette suggestion !
